### ISSUE TITLE
Add ability to start and stop recording video by click

### ISSUE THREAD

**Issue by gouravd** [dewarder/CameraButton#1]
Could you please allow to animate/set state of the button programatically, so that we can emulate the Hold/Release and progress animations programatically too.

We use single tap for recording video and single tap again to stop recording instead of LongPress So currently there is no way to show progress and animation via Single Tap.

**Comment by hluhovskyi** [comment]
Hello! Thanks for applying this issue. 
Feature looks really useful so I am going to handle it. I need time to check some other ways of implementing this functionality. For example maybe it will be better to create new `Mode` instead of directly calling, let's say `startRecord()` and `stopRecord()`.

**Comment by hluhovskyi** [comment]
Added in version 2.0.0. Thanks!

**Comment by gouravd** [comment]
Hi @hluhovskyi Thanks for this...but I was unable to figure out how to handle this..

If I set Mode to 2, the tap/click does not fire the onVideoListener..if I set to 0, then onPhotoListener is fired on tap..but I am unable to get the progress animation

**Comment by hluhovskyi** [comment]
You should also set `cb_collapse_action="click"`. 
By default this property is set to `release` and it means when user clicks/taps on button it immediately collapses (cause click also includes release action in the end). In case if you use action `click` it starts collapse right after user clicks again on the button. 

You should have something like this in your xml:

    <com.hluhovskyi.camerabutton.CameraButton
        android:id="@+id/camera_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:cb_collapse_action="click"
        app:cb_mode="video" />

Or via code:

    button.setMode(CameraButton.Mode.VIDEO)
    button.setCollapseAction(CameraButton.Action.CLICK)

By the way, thanks a lot for bringing up the problem with visibility of `Mode` and `Action`. You should use `Mode.VIDEO` rather than raw value 2.  Version 2.0.1 will be available via maven soon.
